import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

import './globals.css'
 
const roboto = Roboto({
    weight: ['400', '500', '700'],
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="fr">
            <body className={`${roboto.className} antialiased max-h-screen`}>
                {children}
            </body>
        </html>
    )
}
